flows:
  - id: Discovery_of_Insurer_Providers_and_Master_Policies
    tags: ["WORKBENCH", "MANDATORY"]
    description: Discovery of Insurer Providers and Master Policies
    sequence:
      - key: search_insurence_provider
        type: search
        unsolicited: false
        pair: on_search_insurence_provider
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: person_id
            label: Enter person id
            type: text
            payloadField: $.message.intent.fulfillment.agent.person.id  
      - key: on_search_insurence_provider 
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
  - id: Discovery_of_Products_from_Master_Policies (Accidental Insurance)
    tags: ["WORKBENCH", "MANDATORY"]
    description: Discovery of Products from Master Policies (Accidental Insurance)
    sequence:
      - key: search_discover_product_accidental
        type: search
        unsolicited: false
        pair: on_search_discover_product_accidental
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: policy_id
            label: Enter Policy ID
            type: text
            payloadField: $.message.intent.provider.tags[*].list[*].value
      - key: on_search_discover_product_accidental 
        type: on_search
        unsolicited: false
        pair: null  
        owner: BPP
        expect: false
  - id: Purchase_Journey_Accidental_Insurance
    tags: ["WORKBENCH", "MANDATORY"]
    description: Purchase Journey Accidental Insurance
    sequence:
      - key: search_purchase_journey_accidental
        type: search
        unsolicited: false
        pair: on_search_purchase_journey_accidental
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: buyer_name
            label: Enter buyer name
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: phone_number
            label: Enter phone number
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: pan_number
            label: Enter pan number
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: dob
            label: Enter date of birth
            type: date
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: gender
            label: Enter gender
            type: select
            values:
              - "Male"
              - "Female"
            default: "Male"
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: email
            label: Enter email
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: sum_insured
            label: Enter sum insured
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
      - key: on_search_purchase_journey_accidental
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: select
        type: select
        unsolicited: false
        pair: on_select_accidental
        owner: BAP
        expect: false
        input:
          - name: select_input
            label: Enter
            type: fis13_select
      - key: on_select_accidental
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: true
      - key: init_accidental
        type: init
        unsolicited: false
        input:
          - name: nominee_name 
            label: Enter nominee name
            type: text
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="NOMINEE_NAME")].value
          - name: nominee_dob 
            label: Enter nominee DOB
            type: date
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="NOMINEE_DOB")].value
          - name: nominee_relation
            label: Enter nominee relationship
            type: text
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="NOMINEE_RELATIONSHIP")].value
          - name: appointee_name
            label: Enter appointee name
            type: text
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="APPOINTEE_NAME")].value
          - name: appointee_relation 
            label: Enter appointee relationship
            type: text
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="APPOINTEE_RELATIONSHIP")].value
          - name: nominee_good_health_declaration 
            label: Enter nominee good health declaration
            type: select
            values:
              - "Yes"
              - "No"
            default: "Yes"
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="GOOD_HEALTH_DECLARATION")].value
        pair: on_init_accidental
        owner: BAP
        expect: false
      - key: on_init_accidental
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm_accidental
        type: confirm
        unsolicited: false
        pair: on_confirm_accidental
        owner: BAP
        expect: false
      - key: on_confirm_accidental
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: on_update_accidental
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
