name: ONDC:RET11
versions:
  - id: 1.2.5
    reporting: false
    usecase:
      - name: F&B
        flows: "./V-1.2.5/F&B/flows/index.yaml"
    supportedActions:
      $ref: "src/config/RET11/V-1.2.5/supportedActions/index.yaml"
  - id: 1.2.0
    reporting: false
    usecase:
      - name: F&B
        flows: "./V-1.2.0/F&B/flows/index.yaml"
    supportedActions:
      $ref: "src/config/RET11/V-1.2.0/supportedActions/index.yaml"
