flows:
  - id: Discovery_of_Insurer_Providers_and_Master_Policies
    tags: ["WORKBENCH", "MANDATORY"]
    description: Discovery of Insurer Providers and Master Policies
    sequence:
      - key: search_insurence_hospicash_provider
        type: search
        unsolicited: false
        pair: on_search_insurence_provider_hospicash
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: person_id
            label: Enter person id
            type: text
            payloadField: $.message.intent.fulfillment.agent.person.id  
      - key: on_search_insurence_provider_hospicash 
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
  - id: Discovery_of_Products_from_Master_Policies (Hospicash Insurance)
    tags: ["WORKBENCH", "MANDATORY"]
    description: Discovery of Products from Master Policies (Hospicash Insurance)
    sequence:
      - key: search_discover_product_hospicash
        type: search
        unsolicited: false
        pair: on_search_discover_product_hospicash
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: policy_name
            label: Enter Policy
            type: text
            payloadField: $.message.catalog.descriptor.name
      - key: on_search_discover_product_hospicash 
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
  - id: Purchase_Journey_Hospicash_Insurance
    tags: ["PRAMAAN", "MANDATORY", "REPORTABLE", "WORKBENCH"]
    description: Purchase Journey Hospicash Insurance
    sequence:
      - key: search_purchase_journey_hospicash
        type: search
        unsolicited: false
        pair: on_search_purchase_journey_hospicash
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: buyer_name
            label: Enter buyer name
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: phone_number
            label: Enter phone number
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: pan_number
            label: Enter pan number
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: dob
            label: Enter date of birth
            type: date
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: gender
            label: Enter gender
            type: select
            values:
              - "Male"
              - "Female"
            default: "Male"
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: email
            label: Enter email
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: sum_insured
            label: Enter sum insured
            type: text
            payloadField: $.message.intent.provider.items[*].list[*].value
          - name: policy_id
            label: Enter policy id
            type: text
            payloadField: $.message.intent.provider.tags[?(@.descriptor.code=="MASTER_POLICY")].list[?(@.descriptor.code=="POLICY_ID")].value
  
      - key: on_search_purchase_journey_hospicash
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: select
        type: select
        unsolicited: false
        pair: on_select_hospicash
        owner: BAP
        expect: false
        input:
          - name: select_input
            label: Enter
            type: fis13_select
      - key: on_select_hospicash
        type: on_select
        unsolicited: false
        pair: null
        owner: BPP
        expect: true
      - key: init_hospicash
        type: init
        unsolicited: false
        input:
          - name: nominee_name 
            label: Enter nominee name
            type: text
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="NOMINEE_NAME")].value
          - name: nominee_dob 
            label: Enter nominee DOB
            type: date
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="NOMINEE_DOB")].value
          - name: nominee_appointee_name
            label: Enter nominee appointee name
            type: text
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="APPOINTEE_NAME")].value
          - name: nominee_appointee_dob 
            label: Enter nominee appointee DOB
            type: date
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="APPOINTEE_DOB")].value
          - name: nominee_good_health_declaration 
            label: Enter nominee good health declaration
            type: select
            values:
              - "Yes"
              - "No"
            default: "Yes"
            payloadField: $.message.order.fulfillments[*].tags[*].list[?(@.descriptor.code=="GOOD_HEALTH_DECLARATION")].value
        pair: on_init_hospicash
        owner: BAP
        expect: false
      - key: on_init_hospicash
        type: on_init
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: confirm_hospicash
        type: confirm
        unsolicited: false
        pair: on_confirm_hospicash
        owner: BAP
        expect: false
      - key: on_confirm_hospicash
        type: on_confirm
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: on_update_hospicash
        type: on_update
        unsolicited: true
        pair: null
        owner: BPP
        expect: false