supportedActions:
  "": ["search", "select"]
  "null": ["search", "select"]
  search: ["on_search"]
  on_search: ["search", "select", "init", "on_search"]
  select: ["on_select"]
  on_select: ["init", "select"]
  init: ["on_init"]
  on_init: ["init", "confirm"]
  confirm: ["on_confirm", "status"]
  on_confirm: ["confirm", "status", "cancel", "on_update", "on_status", "track", "update"]
  update: ["on_update","on_confirm", "update", "on_status"]
  on_update: ["status","on_confirm", "on_status", "track", "cancel", "update", "on_update"]
  status: ["on_status"]
  track: ["on_track"]
  on_track: ["on_track", "status", "on_status"]
  on_status:
    [
      "status",
      "cancel",
      "track",
      "on_status",
      "on_cancel",
      "on_track",
      "update",
      "on_update",
    ]
  cancel: ["on_cancel", "status"]
  on_cancel: ["cancel", "status", "on_status"]

apiProperties:
  search:
    async_predecessor: null
    transaction_partner: []
  on_search:
    async_predecessor: null
    transaction_partner: ["search"]
  select:
    async_predecessor: null
    transaction_partner: []
  on_select:
    async_predecessor: "select"
    transaction_partner: ["select"]
  init:
    async_predecessor: null
    transaction_partner: []
  on_init:
    async_predecessor: "init"
    transaction_partner: ["init"]
  confirm:
    async_predecessor: null
    transaction_partner: ["init", "on_init"]
  on_confirm:
    async_predecessor: "confirm"
    transaction_partner: ["init", "on_init", "confirm"]
  status:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  on_status:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  update:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  on_update:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  cancel:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  on_cancel:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  track:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  on_track:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm", "track"]
