flows:
  - id: STATION_CODE_FLOW_CATALOG
    description: User uses station code for searching metro
    sequence:
      - key: search1
        type: search
        unsolicited: false
        description:
          User searches over the network to avail the metro mode of transport
          in the city
        pair: on_search1
        owner: BAP
        expect: true
      - key: on_search1
        type: on_search
        unsolicited: false
        description: Response with all station codes
        pair: null
        owner: BPP
  - id: STATION_CODE_FLOW_ORDER
    description: User uses station code for searching metro
    sequence:
      - key: search1
        type: search
        unsolicited: false
        description:
          User searches over the network to avail the metro mode of transport
          in the city
        pair: on_search1
        owner: BAP
        expect: true
      - key: on_search1
        type: on_search
        unsolicited: false
        description: Response with all station codes
        pair: null
        owner: BPP
      - key: search2
        type: search
        unsolicited: false
        description:
          User searches over the network to avail the metro mode of transport
          from one station to another
        pair: on_search2
        owner: BAP
        expect: false
        input:
          - name: vehicle_category
            label: Select vehicle category
            type: select
            values:
              - METRO
            payloadField: $.message.intent.fulfillment.vehicle.category
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: start_code
            label: Enter start station code
            type: text
            payloadField: $.message.intent.fulfillment.stops[?(@.type=='START')].location.descriptor.code
          - name: end_code
            label: Enter end station code
            type: text
            payloadField: $.message.intent.fulfillment.stops[?(@.type=='END')].location.descriptor.code
          - name: bpp_id
            label: enter your bpp_id
            type: text
            payloadField: $.context.bpp_id
      - key: on_search2
        type: on_search
        unsolicited: false
        description: Response with start and end station code
        pair: null
        owner: BPP
      - key: select
        type: select
        unsolicited: false
        description: User selects the station code
        pair: on_select
        owner: BAP
      - key: on_select
        type: on_select
        unsolicited: false
        description: Response with selected station code
        pair: null
        owner: BPP
      - key: init
        type: init
        unsolicited: false
        description:
          Consumer platform shares the terms of order and initializes the
          order
        pair: on_init
        owner: BAP
      - key: on_init
        type: on_init
        unsolicited: false
        description:
          Provider platform accepts the terms of orders and appends its own
          terms and responds with the final draft
        pair: null
        owner: BPP
      - key: confirm
        type: confirm
        unsolicited: false
        description:
          Consumer platform confirms the booking and provides all information
          required for confirmation as per the terms of order
        pair: on_confirm
        owner: BAP
      - key: on_confirm
        type: on_confirm
        unsolicited: false
        description:
          Provider platform confirms the order and provides details of the
          journey on confirmation
        pair: null
        owner: BPP
      - key: status
        type: status
        unsolicited: false
        description: Consumer platform requests for the status of the order
        pair: on_status
        owner: BAP
      - key: on_status
        type: on_status
        unsolicited: false
        description: Provider platform responds with the status of the order
        pair: null
        owner: BPP
  - id: TECHNICAL_CANCELLATION_FLOW
    description: User cancels the metro booking
    sequence:
      - key: search1
        type: search
        unsolicited: false
        description:
          User searches over the network to avail the metro mode of transport
          in the city
        pair: on_search1
        owner: BAP
        expect: true
      - key: on_search1
        type: on_search
        unsolicited: false
        description: Response with all station codes
        pair: null
        owner: BPP
      - key: search2
        type: search
        unsolicited: false
        description:
          User searches over the network to avail the metro mode of transport
          from one station to another
        pair: on_search2
        owner: BAP
        expect: false
        input:
          - name: vehicle_category
            label: Select vehicle category
            type: select
            values:
              - METRO
            payloadField: $.message.intent.fulfillment.vehicle.category
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.context.location.city.code
          - name: start_code
            label: Enter start station code
            type: text
            payloadField: $.message.intent.fulfillment.stops[?(@.type=='START')].location.descriptor.code
          - name: end_code
            label: Enter end station code
            type: text
            payloadField: $.message.intent.fulfillment.stops[?(@.type=='END')].location.descriptor.code
          - name: bpp_id
            label: enter your bpp_id
            type: text
            payloadField: $.context.bpp_id
      - key: on_search2
        type: on_search
        unsolicited: false
        description: Response with start and end station code
        pair: null
        owner: BPP
      - key: select
        type: select
        unsolicited: false
        description: User selects the station code
        pair: on_select
        owner: BAP
      - key: on_select
        type: on_select
        unsolicited: false
        description: Response with selected station code
        pair: null
        owner: BPP
      - key: init
        type: init
        unsolicited: false
        description:
          Consumer platform shares the terms of order and initializes the
          order
        pair: on_init
        owner: BAP
      - key: on_init
        type: on_init
        unsolicited: false
        description:
          Provider platform accepts the terms of orders and appends its own
          terms and responds with the final draft
        pair: null
        owner: BPP
      - key: confirm
        type: confirm
        unsolicited: false
        description:
          Consumer platform confirms the booking and provides all information
          required for confirmation as per the terms of order
        pair: on_confirm_delayed
        owner: BAP
      - key: on_confirm_delayed
        type: on_confirm
        unsolicited: false
        description:
          Provider platform confirms the order and provides details of the
          journey on confirmation
        pair: null
        owner: BPP
      - key: status
        type: status
        unsolicited: false
        description: Consumer platform requests for the status of the order
        pair: on_status
        owner: BAP
      - key: on_status
        type: on_status
        unsolicited: false
        description: Provider platform responds with the status of the order
        pair: null
        owner: BPP
      - key: cancel
        type: cancel
        unsolicited: false
        description: User cancels the booking
        pair: on_cancel_hard
        owner: BAP
      - key: on_cancel_hard
        type: on_cancel
        unsolicited: false
        description:
          Provider platform cancels the booking and provides the details of
          the cancellation
        pair: null
        owner: BPP
