flows:
  - type: playground
    id: Order_to_confirm_to_fulfillment_(Prepaid)
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Delivery Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Order_to_confirm_to_fulfillment_(Prepaid).yaml"
  - type: playground
    id: Buyer_Side_Order_Cancellation
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Cancellation Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Buyer_Side_Order_Cancellation.yaml"
  - type: playground
    id: Search_and_Custom_Menu_(Full_Catalog_City)
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Discovery Flow (Full Catalog) for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Search_and_Custom_Menu_(Full_Catalog_City).yaml"
  - type: playground
    id: Search_and_Custom_Menu_(Incremental_Push)
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Discovery Flow (Incremental Catalog) for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Search_and_Custom_Menu_(Incremental_Push).yaml"
  - type: playground
    id: Out_of_Stock(Error_code)
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Out of Stock Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Out_of_Stock(Error_code).yaml"
  - type: playground
    id: Buyer_Initiated_Return_(Full_Order_and_Partial_Order)
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Return Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Buyer_Initiated_Return_(Full_Order_and_Partial_Order).yaml"
  - type: playground
    id: Merchant_Side_RTO_and_Part_Order_Cancellation_Flow
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: RTO and Part Cancellation Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Merchant_Side_RTO_and_Part_Order_Cancellation_Flow.yaml"
