flows:
  - type: playground
    id: Delivery_Flow
    tags: ["WORKBENCH"]
    description: Delivery Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Delivery_Flow.yaml"
  - type: playground
    id: Cancellation_Flow
    tags: ["WORKBENCH"]
    description: Cancellation Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Cancellation_Flow.yaml"
  - type: playground
    id: Discovery_Flow_full_catalog
    tags: ["WORKBENCH"]
    description: Discovery Flow (Full Catalog) for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Discovery_Flow_full_catalog.yaml"
  - type: playground
    id: Discovery_Flow_incremental_catalog
    tags: ["WORKBENCH"]
    description: Discovery Flow (Incremental Catalog) for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Discovery_Flow_incremental_catalog.yaml"
  - type: playground
    id: Out_of_Stock_Flow
    tags: ["WORKBENCH"]
    description: Out of Stock Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Out_of_Stock_Flow.yaml"
  - type: playground
    id: Return_Flow
    tags: ["WORKBENCH"]
    description: Return Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/Return_Flow.yaml"
  - type: playground
    id: RTO_And_Part_Cancellation_Flow
    tags: ["WORKBENCH"]
    description: RTO and Part Cancellation Flow for Grocery
    config:
      $ref: "src/config/RET10/v-1.2.0/GROCERY/flows/RTO_And_Part_Cancellation_Flow.yaml"
