supportedActions:
  null: ["search", "select", "init"]
  search: ["on_search","search"]
  on_search: ["search", "select", "init", "on_search"]
  select: ["on_select"]
  on_select: ["select", "init"]
  init: ["on_init"]
  on_init: ["init", "confirm"]
  confirm: ["on_confirm", "status"]
  on_confirm: ["confirm", "status", "cancel", "on_status", "update", "issue","on_cancel"]
  status: ["on_status"]
  on_status: ["status", "cancel", "issue", "on_status"]
  cancel: ["on_cancel", "status", "on_update", "on_status"]
  on_cancel: ["cancel", "status", "on_update", "on_status"]
  update: ["on_update"]
  on_update: ["on_cancel", "update", "on_status", "cancel"]
  issue: ["on_issue", "issue", "on_update", "on_status", "on_confirm", "on_issue_status"]
  on_issue: ["issue", "on_issue", "on_status", "on_issue_status"]
  on_issue_status: ["on_issue", "issue"]

apiProperties:
  search:
    async_predecessor: null
    transaction_partner: []
  on_search:
    async_predecessor: null
    transaction_partner: ["search"]
  select:
    async_predecessor: null
    transaction_partner: []
  on_select:
    async_predecessor: "select"
    transaction_partner: ["select"]
  init:
    async_predecessor: null
    transaction_partner: []
  on_init:
    async_predecessor: "init"
    transaction_partner: ["init"]
  confirm:
    async_predecessor: null
    transaction_partner: ["init", "on_init"]
  on_confirm:
    async_predecessor: "confirm"
    transaction_partner: ["init", "on_init", "confirm"]
  status:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm"]
  on_status:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm"]
  cancel:
    async_predecessor: null
    transaction_partner: ["confirm"]
  on_cancel:
    async_predecessor: null
    transaction_partner: ["confirm"]
  update:
    async_predecessor: null
    transaction_partner: []
  on_update:
    async_predecessor: null
    transaction_partner: []
