domain:
  - name: ONDC:TRV11
    versions:
      - id: 2.0.0
        reporting: true
        usecase:
          - name: Metro
            flows: "./TRV11/V-2.0.0/metro/flows/index.yaml"
          - name: Bus
            flows: "./TRV11/V-2.0.0/bus/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV11/V-2.0.0/supportedActions/index.yaml"
      - id: 2.0.1
        reporting: true
        usecase:
          - name: Metro
            flows: "./TRV11/V-2.0.1/metro/flows/index.yaml"
          - name: Bus
            flows: "./TRV11/V-2.0.1/bus/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV11/V-2.0.1/supportedActions/index.yaml"
  - name: ONDC:TRV10
    versions:
      - id: 2.1.0
        reporting: false
        usecase:
          - name: Ride-hailing
            flows: "./TRV10/V-2.1.0/ride-hailing/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV10/V-2.1.0/supportedActions/index.yaml"
  - name: ONDC:TRV14
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: unreserved-entry-pass
            flows: "./TRV14/V-2.0.0/unreserved-ticketing/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV14/V-2.0.0/supportedActions/index.yaml"
  - name: ONDC:LOG10
    versions:
      - id: 1.2.5
        reporting: true
        usecase:
          - name: Logistics (P2P)
            flows: "./LOG10/V-1.2.5/logistics/flows/index.yaml"
        supportedActions:
          $ref: "src/config/LOG10/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:LOG11
    versions:
      - id: 1.2.5
        reporting: true
        usecase:
          - name: Logistics (P2H2P)
            flows: "./LOG11/V-1.2.5/logistics/flows/index.yaml"
        supportedActions:
          $ref: "src/config/LOG11/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET11
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: F&B
            flows: "./RET11/V-1.2.5/F&B/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET11/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET10
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: GROCERY
            flows: "./RET10/v-1.2.5/GROCERY/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET10/v-1.2.5/supportedActions/index.yaml"
  - name: ONDC:TRV14
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: Entry-Pass
            flows: "./TRV14/V-2.0.0/entry-pass/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV14/V-2.0.0/supportedActions/index.yaml"
  - name: ONDC:RET12
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: FASHION
            flows: "./RET13/V-1.2.5/BPC/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET13/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET13
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: BPC
            flows: "./RET13/V-1.2.5/BPC/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET13/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET14
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: ELECTRONICS
            flows: "./RET14/v-1.2.5/ELECTRONICS/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET14/v-1.2.5/supportedActions/index.yaml"
  - name: ONDC:FIS14
    versions:
      - id: 2.1.0
        reporting: false
        usecase:
          - name: MUTUAL FUNDS
            flows: "./FIS14/V-2.1.0/mutualFunds/flows/index.yaml"
        supportedActions:
          $ref: "src/config/FIS14/V-2.1.0/supportedActions/index.yaml"
  - name: ONDC:FIS10
    versions:
      - id: 2.1.0
        reporting: false
        usecase:
          - name: GIFT CARDS
            flows: "./FIS10/V-2.1.0/giftCard/flows/index.yaml"
        supportedActions:
          $ref: "src/config/FIS10/V-2.1.0/supportedActions/index.yaml"
  - name: ONDC:FIS12
    versions:
      - id: 2.0.2
        reporting: false
        usecase:
          - name: GOLD LOAN
            flows: "./FIS12/V-2.0.2/goldLoan/flows/index.yaml"
        supportedActions:
          $ref: "src/config/FIS12/V-2.0.2/supportedActions/index.yaml"
usecases:
  domain:
    - key: ONDC:TRV11
      version:
        - key: 2.0.0
          usecase:
            - Metro
            - Bus
        - key: 2.0.1
          usecase:
            - Metro
            - Bus
    - key: ONDC:TRV10
      version:
        - key: 2.1.0
          usecase:
            - Ride-hailing
    
    - key: ONDC:TRV14
      version:
        - key: 2.0.0
          usecase:
            - unreserved-entry-pass
    - key: ONDC:LOG10
      version:
        - key: 1.2.5
          usecase:
            - Logistics (P2P)
    - key: ONDC:LOG11
      version:
        - key: 1.2.5
          usecase:
            - Logistics (P2H2P)
    - key: ONDC:RET10
      version:
        - key: 1.2.5
          usecase:
            - GROCERY
    - key: ONDC:RET11
      version:
        - key: 1.2.5
          usecase:
            - F&B
    - key: ONDC:RET12
      version:
        - key: 1.2.5
          usecase:
            - FASHION
    - key: ONDC:RET13
      version:
        - key: 1.2.5
          usecase:
            - BPC
    - key: ONDC:RET14
      version:
        - key: 1.2.5
          usecase:
            - ELECTRONICS
    - key: ONDC:FIS14
      version:
        - key: 2.1.0
          usecase:
            - MUTUAL FUNDS
    - key: ONDC:FIS10
      version:
        - key: 2.1.0
          usecase:
            - GIFT CARDS
    - key: ONDC:FIS12
      version:
        - key: 2.0.2
          usecase:
            - GOLD LOAN
