domain:
  - name: ONDC:TRV11
    versions:
    #   - id: 2.0.0
    #     reporting: true
    #     usecase:
    #       - name: Metro
    #         flows: "./TRV11/V-2.0.0/metro/flows/index.yaml"
    #       - name: Bus
    #         flows: "./TRV11/V-2.0.0/bus/flows/index.yaml"
    #     supportedActions:
    #       $ref: "src/config/TRV11/V-2.0.0/supportedActions/index.yaml"
      - id: 2.0.1
        usecase:
          - name: Metro
            flows: "./TRV11/V-2.0.1/metro/flows/index.yaml"
          - name: Bus
            flows: "./TRV11/V-2.0.1/bus/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV11/V-2.0.1/supportedActions/index.yaml"
    supportedActions:
      $ref: "src/config/TRV11/V-2.0.1/supportedActions/index.yaml"
  - name: ONDC:TRV14
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: unreserved-entry-pass
            flows: "./TRV14/V-2.0.0/unreserved-ticketing/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV14/V-2.0.0/supportedActions/index.yaml"
  - name: ONDC:TRV12
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: Airline
            flows: "./TRV12/V-2.0.0/airline/flows/index.yaml"
          - name: Intercity
            flows: "./TRV12/V-2.0.0/intercity/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV12/V-2.0.0/supportedActions/index.yaml"        
  - name: ONDC:TRV13
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: Hotel-Booking
            flows: "./TRV13/V-2.0.0/hotel-booking/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV13/V-2.0.0/supportedActions/index.yaml" 
      - id: 2.0.1
        reporting: false
        usecase:
          - name: Hotel-Booking-V2
            flows: "./TRV13/V-2.0.1/hotel-booking/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV13/V-2.0.1/supportedActions/index.yaml"           
  - name: ONDC:LOG10
    versions:
      - id: 1.2.5
        reporting: true
        usecase:
          - name: Logistics (P2P)
            flows: "./LOG10/V-1.2.5/logistics/flows/index.yaml"
        supportedActions:
          $ref: "src/config/LOG10/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:LOG11
    versions:
      - id: 1.2.5
        reporting: true
        usecase:
          - name: Logistics (P2H2P)
            flows: "./LOG11/V-1.2.5/logistics/flows/index.yaml"
        supportedActions:
          $ref: "src/config/LOG11/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:TRV10
    versions:
      - id: 2.1.0
        usecase:
          - name: Ride-hailing
            flows: "./TRV10/V-2.1.0/ride-hailing/flows/index.yaml"
        supportedActions:
          $ref: "src/config/TRV10/V-2.1.0/supportedActions/index.yaml"
  - name: ONDC:RET11
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: F&B
            flows: "./RET11/V-1.2.5/F&B/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET11/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET10
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: GROCERY
            flows: "./RET10/v-1.2.5/GROCERY/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET10/v-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET12
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: FASHION
            flows: "./RET12/V-1.2.5/FASHION/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET12/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET13
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: BPC
            flows: "./RET13/V-1.2.5/BPC/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET13/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET14
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: ELECTRONICS
            flows: "./RET14/v-1.2.5/ELECTRONICS/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET14/v-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET15
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: APPLIANCES
            flows: "./RET15/v-1.2.5/APPLIANCES/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET15/v-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET16
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: HOME&KITCHEN
            flows: "./RET16/v-1.2.5/HOME&KITCHEN/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET16/v-1.2.5/supportedActions/index.yaml"
  - name: ONDC:RET18
    versions:
      - id: 1.2.5
        reporting: false
        usecase:
          - name: HEALTH&WELLNESS
            flows: "./RET18/V-1.2.5/Health&Wellness/flows/index.yaml"
        supportedActions:
          $ref: "src/config/RET18/V-1.2.5/supportedActions/index.yaml"
  - name: ONDC:FIS11
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: metro-card-recharge
            flows: "./FIS11/V-2.0.0/metroCardRecharge/flows/index.yaml"
        supportedActions:
          $ref: "src/config/FIS11/V-2.0.0/supportedActions/index.yaml"
  - name: ONDC:FIS12
    versions:
      - id: 2.0.2
        reporting: false
        usecase:
          - name: GOLD LOAN
            flows: "./FIS12/V-2.0.2/goldLoan/flows/index.yaml"
        supportedActions:
          $ref: "src/config/FIS12/V-2.0.2/supportedActions/index.yaml"        
  - name: ONDC:FIS13
    versions:
      - id: 2.0.0
        reporting: false
        usecase:
          - name: transit-insurance
            flows: "./FIS13/V-2.0.0/transit-insurance/flows/index.yaml"
          - name: accidental-insurance
            flows: "./FIS13/V-2.0.0/accidental-insurance/flows/index.yaml"
          - name: hospicash-insurance
            flows: "./FIS13/V-2.0.0/hospicash-insurance/flows/index.yaml"
        supportedActions:
          $ref: "src/config/FIS13/V-2.0.0/supportedActions/index.yaml"   
usecases:
  domain:
    - key: ONDC:TRV11
      version:
        # - key: 2.0.0
        #   usecase:
        #     - Metro
        #     - Bus
        - key: 2.0.1
          usecase:
            - Metro
            - Bus
    - key: ONDC:LOG10
      version:
        - key: 1.2.5
          usecase:
            - Logistics (P2P)
    - key: ONDC:LOG11
      version:
        - key: 1.2.5
          usecase:
            - Logistics (P2H2P)
    - key: ONDC:TRV10
      version:
        - key: 2.1.0
          usecase:
            - Ride-hailing
    - key: ONDC:RET11
      version:
        - key: 1.2.5
          usecase:
            - F&B
    - key: ONDC:TRV13
      version:
        - key: 2.0.0
          usecase:
            - Hotel-Booking 
        - key: 2.0.1
          usecase:
            - Hotel-Booking-V2 
    - key: ONDC:TRV12
      version:
        - key: 2.0.0
          usecase:
            - Intercity       
            - Airline                  
    - key: ONDC:RET10
      version:
        - key: 1.2.5
          usecase:
            - GROCERY
    - key: ONDC:RET12
      version:
        - key: 1.2.5
          usecase:
            - FASHION
    - key: ONDC:RET13
      version:
        - key: 1.2.5
          usecase:
            - BPC
    - key: ONDC:RET14
      version:
        - key: 1.2.5
          usecase:
            - ELECTRONICS
    - key: ONDC:TRV14
      version:
        - key: 2.0.0
          usecase:
            - unreserved-entry-pass
    - key: ONDC:RET15
      version:
        - key: 1.2.5
          usecase:
            - APPLIANCES
    - key: ONDC:RET16
      version:
        - key: 1.2.5
          usecase:
            - HOME&KITCHEN
    - key: ONDC:RET18
      version:
        - key: 1.2.5
          usecase:
            - HEALTH&WELLNESS
    - key: ONDC:FIS11
      version:
        - key: 2.0.0
          usecase:
            - metro-card-recharge
    - key: ONDC:FIS12
      version:
        - key: 2.0.2
          usecase:
            - GOLD LOAN     
    - key: ONDC:FIS13
      version:
        - key: 2.0.0
          usecase:
            - transit-insurance
            - accidental-insurance
            - hospicash-insurance  