flows:
  - type: playground
    id: Order_to_confirm_to_fulfillment_(Prepaid)
    tags: ["WORKBENCH","PRAMAAN", "MANDATORY", "REPORTABLE"]
    description: Discovery Flow for EB2B
    config:
      $ref: "src/config/RETeB2B/v-1.2.5/EB2B/flows/Discovery_flow_broadcast_search.yaml"