supportedActions:
  null: ["search"]
  search: ["on_search"]
  on_search: ["search", "select"]
  select: ["on_select"]
  on_select: ["select","init","on_status"]
  init: ["on_init"]
  on_init: ["init", "confirm"]
  confirm: ["on_confirm", "status"]
  on_confirm: ["status", "cancel", "on_status", "on_update","update","on_cancel"]
  status: ["on_status"]
  on_status: ["select","status", "cancel", "on_update","track","on_status","update","on_select"]
  on_update: ["status","update","on_status","track","on_confirm","on_update","cancel"]
  cancel: ["on_cancel", "status"]
  on_cancel: ["cancel", "status","on_status","on_update"]
  track: ["on_track"]
  on_track: ["on_status","on_update"]
  update: ["on_update"]

apiProperties:
  search:
    async_predecessor: null
    transaction_partner: []
  on_search:
    async_predecessor: null
    transaction_partner: ["search"]
  select:
    async_predecessor: null
    transaction_partner: ["search"]
  on_select:
    async_predecessor: null
    transaction_partner: ["select", "search", "on_search"]
  init:
    async_predecessor: null
    transaction_partner: ["select", "search", "on_search", "on_select"]
  on_init:
    async_predecessor: "init"
    transaction_partner: ["init", "select", "search", "on_search", "on_select"]
  confirm:
    async_predecessor: null
    transaction_partner: ["init", "on_init"]
  on_confirm:
    async_predecessor: "confirm"
    transaction_partner: ["init", "on_init", "confirm"]
  status:
    async_predecessor: null
    transaction_partner: ["on_status"]
  on_status:
    async_predecessor: null
    transaction_partner: ["on_select"]
  cancel:
    async_predecessor: null
    transaction_partner: ["confirm", "on_confirm","on_update"]
  on_cancel:
    async_predecessor: null
    transaction_partner: ["confirm","on_confirm","cancel"]
  track:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  on_track:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  update:
    async_predecessor: null
    transaction_partner: []
  on_update:
    async_predecessor: null
    transaction_partner: ["on_confirm"]
