supportedActions:
  null: ["search", "on_select", "select"]
  search: ["on_search"]
  on_search: ["search", "select", "init", "on_search"]
  select: ["on_select"]
  on_select: ["init", "select"]
  init: ["on_init"]
  on_init: ["init", "confirm"]
  confirm: ["on_confirm", "status"]
  on_confirm:
    ["status", "cancel", "on_status", "on_update", "update", "on_cancel"]
  status: ["on_status"]
  on_status:
    ["status", "cancel", "on_update", "track", "on_status", "update", "rating"]
  on_update: ["status", "update", "on_status", "track", "cancel", "on_cancel"]
  cancel: ["on_cancel", "status", "on_confirm"]
  on_cancel: ["cancel", "status", "on_status"]
  track: ["on_track"]
  on_track: ["on_status", "on_update"]
  update: ["on_update"]
  rating: ["on_rating"]

apiProperties:
  search:
    async_predecessor: null
    transaction_partner: []
  on_search:
    async_predecessor: null
    transaction_partner: ["search"]
  select:
    async_predecessor: null
    transaction_partner: []
  on_select:
    async_predecessor: "select"
    transaction_partner: ["select"]
  init:
    async_predecessor: null
    transaction_partner: ["select", "on_select"]
  on_init:
    async_predecessor: "init"
    transaction_partner: ["init", "select", "on_select"]
  confirm:
    async_predecessor: null
    transaction_partner: ["init", "on_init"]
  on_confirm:
    async_predecessor: "confirm"
    transaction_partner: ["init", "on_init", "confirm"]
  status:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm"]
  on_status:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  cancel:
    async_predecessor: null
    transaction_partner: ["confirm", "on_confirm"]
  on_cancel:
    async_predecessor: null
    transaction_partner: ["confirm", "on_confirm", "cancel"]
  track:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  on_track:
    async_predecessor: null
    transaction_partner: ["init", "on_init", "confirm", "on_confirm"]
  update:
    async_predecessor: null
    transaction_partner: ["confirm", "on_confirm"]
  on_update:
    async_predecessor: "update"
    transaction_partner: ["update"]
rating:
  async_predecessor: "on_status"
  transaction_partner: ["on_status"]
